{{- if .Values.room.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ .Release.Name }}room"
  annotations:
    {{- range $key, $value := .Values.room.ingress.annotations }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: {{ .Values.room.ingress.className }}
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: "{{ .Release.Name }}room"
              port:
                number: {{ .Values.room.service.port }}
  {{- if .Values.room.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.room.ingress.hostname }}
    secretName: {{ .Values.room.ingress.tls.secretName }}
  {{- end }}
{{- end }}
---
{{- if .Values.lobby.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ .Release.Name }}lobby"
  annotations:
    {{- range $key, $value := .Values.lobby.ingress.annotations }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: {{ .Values.lobby.ingress.className }}
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: "{{ .Release.Name }}lobby"
              port:
                number: {{ .Values.lobby.service.port }}
  {{- if .Values.lobby.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.lobby.ingress.hostname }}
    secretName: {{ .Values.lobby.ingress.tls.secretName }}
  {{- end }}
{{- end }}