apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ .Release.Name }}room"
  labels:
    app: "{{ .Release.Name }}room"
spec:
  type: {{ .Values.room.service.type }}
  ports:
  - port: {{ .Values.room.service.port }}
    targetPort: {{ .Values.room.service.targetport }}
    protocol: {{ .Values.room.service.protocol }}
  selector:
    app: "{{ .Release.Name }}room"
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ .Release.Name }}lobby"
  labels:
    app: "{{ .Release.Name }}lobby"
spec:
  type: {{ .Values.lobby.service.type }}
  ports:
  - port: {{ .Values.lobby.service.port }}
    targetPort: {{ .Values.lobby.service.targetport }}
    protocol: {{ .Values.lobby.service.protocol }}
  selector:
    app: "{{ .Release.Name }}lobby"
