{{- if .Values.room.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ .Release.Name }}"
  annotations:
    {{- range $key, $value := .Values.room.ingress.annotations }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    external-dns.alpha.kubernetes.io/hostname: "room.semesterarbeit.com"
spec:
  ingressClassName: {{ .Values.room.ingress.className }}
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: "{{ .Release.Name }}"
              port:
                number: {{ .Values.room.service.port }}
  {{- if .Values.room.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.room.ingress.hostname }}
    secretName: {{ .Values.room.ingress.tls.secretName }}
  {{- end }}
{{- end }}
