apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
spec:
  type: {{ .Values.room.service.type }}
  ports:
  - port: {{ .Values.room.service.port }}
    targetPort: {{ .Values.room.service.targetport }}
    protocol: {{ .Values.room.service.protocol }}
  selector:
    app: "{{ .Release.Name }}"
